#!/usr/bin/env php
<?php
if (count($argv) != 3) {
  warn(usage());
  exit(1);
}

$dir1 = rtrim($argv[1], '/');
$dir2 = rtrim($argv[2], '/');

foreach ([$dir1, $dir2] as $dir) {
  if (!is_dir($dir)) {
    warn("No directory {$dir}.");
    exit(2);
  }
}

$files_by_md5sum = [];
foreach ([$dir1, $dir2] as $dir) {
  foreach (glob("{$dir}/*") as $file) {
    $md5sum = md5_file($file);
    if (!array_key_exists($md5sum, $files_by_md5sum)) {
      $files_by_md5sum[$md5sum] = [];
    }
    $files_by_md5sum[$md5sum][] = $file;
  }
}

$only_in_dir1 = [];
$only_in_dir2 = [];
$common = [];

foreach ($files_by_md5sum as $md5sum => $files) {
  $count_dir1 = 0;
  $count_dir2 = 0;
  foreach ($files as $file) {
    if (str_starts_with($file, $dir1)) {
      ++$count_dir1;
    } else {
      ++$count_dir2;
    }
  }
  if ($count_dir1 && $count_dir2) {
    $common[] = $md5sum;
  } else if ($count_dir1) {
    $only_in_dir1[] = $md5sum;
  } else {
    $only_in_dir2[] = $md5sum;
  }
}

if (!$only_in_dir1 && !$only_in_dir2) {
  echo "Directories contain the same files.\n";
  exit(0);
}


if ($only_in_dir1) {
  echo "ONLY IN {$dir1} (".count($only_in_dir1)."):\n";
  foreach ($only_in_dir1 as $md5sum) {
    echo "  - ", implode(' = ', $files_by_md5sum[$md5sum]), "\n";
  }
}
if ($only_in_dir2) {
  echo "ONLY IN {$dir2} (".count($only_in_dir2)."):\n";
  foreach ($only_in_dir2 as $md5sum) {
    echo "  - ", implode(' = ', $files_by_md5sum[$md5sum]), "\n";
  }
}
if ($common) {
  echo "COMMON: (".count($common).")\n";
  foreach ($common as $md5sum) {
    echo "  - ", implode(' = ', $files_by_md5sum[$md5sum]), "\n";
  }
}


function warn($s) {
  fwrite(STDERR, $s."\n");
}


function usage() {
  global $argv;
  $script = basename($argv[0]);
  return <<<EOF
Usage:
  $script dir1 dir2
EOF;
}
