#!/bin/bash

if (( $# < 2 )); then
  echo >&2 "Usage: $(basename -- "$0") dbfile dumpfile ..."
  exit 1
fi

dbfile=$1
if [[ ! -f $dbfile ]]; then
  echo >&2 "No file $dbfile."
  exit 1
fi
if [[ $(head -c 6 "$dbfile") != "SQLite" ]]; then
  echo >&2 "$dbfile is no SQLite file."
  exit 1
fi
shift

for sqlfile; do
  if ! [[ -f $sqlfile ]]; then
    echo >&2 "No file $sqlfile."
    exit 1
  fi
done

{
  cat - "$@" <<EOF
.output /dev/null
PRAGMA journal_mode = OFF;
PRAGMA synchronous = OFF;
.output stdout
EOF
} | sqlite3 "$dbfile"

