#!/bin/bash

if [ $# -ne 1 ]; then
  echo >&2 "Usage: $(basename -- "$0") dbfile"
  exit 1
fi

dbfile=$1
if [[ ! -f $dbfile ]]; then
  echo >&2 "No file $dbfile."
  exit 1
fi

{
  for table in $(sqlite3 "$dbfile" .tables); do
    echo ".mode insert $table"
    echo "select * from $table;"
  done
} | sqlite3 "$dbfile"

