#!/bin/bash

base=$(basename -- "$0")
if [ $# -ne 2 ]; then
  echo >&2 "Usage: $base file1 file2"
  exit 1
fi

for file; do
  if [[ ! -f "$file" ]]; then
    echo >&2 "$base: no file $file."
    exit 2
  fi
done

tmpfile=$(mktemp)
mv -- "$1" "$tmpfile" && mv -- "$2" "$1" && mv "$tmpfile" "$2"

