#!/bin/bash

keyringdir="/etc/apt/keyrings"
[[ -d $keyringdir ]] || sudo mkdir -p "$keyringdir"

key_url="https://download.mono-project.com/repo/xamarin.gpg"
target="$keyringdir/mono.gpg"
source_list="/etc/apt/sources.list.d/mono-official-stable.list"

# make sure keyring file is referenced in source list, e.g.:
# deb [arch=amd64,signed-by=/etc/apt/keyrings/skype-keyring.gpg] https://repo.skype.com/deb stable main
if ! grep -q "signed-by=$target" "$source_list"; then
  echo >&2 "Error: $target is not configured as keyring file in $source_list, should be:"
  echo >&2 "deb [... signed-by=$target ...] ..."
  exit 1
fi

echo "Downloading GPG key from $key_url to $target ..."
wget -qO - "$key_url" \
  | gpg --dearmor \
  | sudo tee "$target" >/dev/null
